version: '3.8'

services:
  server:
    image: dos-server
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: dos-server
    volumes:
      - "./server/conf/nginx/default.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8185:80"
    networks:
      - custom-net

networks:
  custom-net:
    driver: bridge